import React from "react";
import {FaItunesNote} from "react-icons/fa";
import {TiArrowBackOutline} from "react-icons/ti";
import {TiBell} from "react-icons/ti";
import {TiDownload} from "react-icons/ti";
import {TiCompass} from "react-icons/ti";
import {TiHeart} from "react-icons/ti";
import {TiPencil} from "react-icons/ti";
import {TiRss} from "react-icons/ti";
import {TiPower} from "react-icons/ti";
import {TiPuzzle} from "react-icons/ti";
import {TiPin} from "react-icons/ti";
import {TiPlug} from "react-icons/ti";
import {TiSocialInstagramCircular} from "react-icons/ti";
import {TiWarning} from "react-icons/ti";
import {TiThumbsUp} from "react-icons/ti";
import {TiWeatherPartlySunny} from "react-icons/ti";
import {TiSocialDribbble} from "react-icons/ti";

export default function Bg (){
    return (
        <div className="absolute left-0 group w-full h-fit md:h-full overflow-hidden">
            <div className="flex flex-col md:flex-row h-fit overflow-hidden">
                <div className="w-fit">
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                </div>
                <div className="w-fit h-full">
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative flex -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative md:flex hidden -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative md:flex hidden -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative md:flex hidden -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative md:flex hidden -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative md:flex hidden -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative md:flex hidden -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative md:flex hidden -rotate-12 -top-72 -left-20">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative md:flex -rotate-12 -top-72 -left-20 hidden">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative md:flex -rotate-12 -top-72 -left-20 hidden">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative md:flex -rotate-12 -top-72 -left-20 hidden">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                    <div className="relative md:flex -rotate-12 -top-72 -left-20 hidden">
                    <FaItunesNote className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiArrowBackOutline className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiBell className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiDownload className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiCompass className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiHeart className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPencil className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiRss className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPower className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialInstagramCircular className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiSocialDribbble className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPuzzle className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPin className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiPlug className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWarning className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiThumbsUp className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    <TiWeatherPartlySunny className="w-[90px] h-[90px] text-gray-800 hover:text-white hover:duration-[50ms] duration-300 drop-shadow-2xl" />
                    </div>
                </div>
            </div>
        </div>
    )    
}